# docker stack deploy -c docker-compose.yml whisper
version: '3.5'

services:

  whisper:
    build: .
    image: abilioesteves/whisper:0.0.1
    ports:
      - "7070:7072"
    environment:
      - WHISPER_PORT=7072

  prometheus:
    image: abilioesteves/prometheus:1.0.0
    ports:
      - 9090:9090
    environment:
      - SCRAPE_INTERVAL=15s
      - SCRAPE_TIMEOUT=10s
      - STATIC_SCRAPE_TARGETS=whisper@whisper:7070/metrics

  grafana:
    image: flaviostutz/grafana
    ports:
      - 3000:3000

