# docker stack deploy -c docker-compose.yml careless-whisper
version: '3.5'

services:

  careless-whisper:
    build: .
    image: abilioesteves/careless-whisper:0.0.1
    ports:
      - "7070:7070"
    environment:
      - PORT=7070

  prometheus:
    image: abilioesteves/prometheus:1.0.0
    ports:
      - 9090:9090
    environment:
      - SCRAPE_INTERVAL=15s
      - SCRAPE_TIMEOUT=10s
      - STATIC_SCRAPE_TARGETS=careless-whisper@careless-whisper:7070/metrics

  grafana:
    image: flaviostutz/grafana
    ports:
      - 3000:3000

